const showsTypes = {
  GET_SHOWS_START: "GET_SHOWS_START",
  GET_SHOWS_SUCCESS: "GET_SHOWS_SUCCESS",
  GET_SHOWS_FAILURE: "GET_SHOWS_FAILURE",
  SET_FAVORITE: "SET_FAVORITE",
};

export default showsTypes;
